name: worklog

volumes:
  pgdata:

networks:
  worklog-network:
    driver: bridge

x-defaults: &defaults
  init: true
  tty: true
  restart: on-failure:2
  networks:
    - worklog-network

services:
  # Сервис базы данных PostgreSQL
  db:
    <<: *defaults
    image: postgres:16-alpine
    container_name: worklog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: worklog_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d worklog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис Fastify API
  api:
    <<: *defaults
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: worklog-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      # - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?schema=public

    depends_on:
      db:
        condition: service_healthy # Ждем, пока Postgres полностью запустится и пройдет healthcheck
