name: worklog

volumes:
  pgdata:

networks:
  worklog-network:
    driver: bridge

# secrets:
#   db_pwd:
#     file: db_pwd.txt # Путь на хосте (в корне проекта)

x-defaults: &defaults
  init: true
  tty: true
  restart: on-failure:2
  networks:
    - worklog-network
  # secrets:
  #   - db_pwd # Подключаем секрет к контейнерам

services:
  # Сервис базы данных PostgreSQL
  db:
    <<: *defaults
    image: postgres:16-alpine
    container_name: worklog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: worklog
    ports:
      - '127.0.0.1:5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d worklog"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис Fastify API
  api:
    <<: *defaults
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: worklog-api
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy # Ожидание запуска и успешного healthcheck контейнера db  
  web:
    container_name: worklog-web
    <<: *defaults    
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "127.0.0.1:5173:80"
    # depends_on:
    #   api:
    #     condition: service_healthy